# Generated by Django 3.1.2 on 2022-10-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('clientId', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('dateNaissance', models.DateTimeField()),
                ('numero_passport', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('log_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='reservation_room',
            fields=[
                ('reservationId', models.AutoField(primary_key=True, serialize=False)),
                ('nom_chambre', models.CharField(max_length=30)),
                ('Checkin', models.DateTimeField()),
                ('Checkout', models.DateTimeField()),
                ('nb_adultes', models.IntegerField()),
                ('nb_enfants', models.IntegerField()),
                ('clientId', models.IntegerField()),
            ],
        ),
    ]
